# Generated by ChatGPT for initial models migration
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When this crossword becomes available', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this crossword is no longer available', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Admin toggle to make crossword visible')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary metadata for UI (e.g., size, theme)')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrosswordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('number', models.PositiveIntegerField(help_text='Clue number')),
                ('direction', models.CharField(choices=[('across', 'Across'), ('down', 'Down')], max_length=5)),
                ('clue', models.TextField()),
                ('answer', models.CharField(help_text='Correct answer in uppercase A-Z only', max_length=128)),
                ('row', models.PositiveIntegerField(help_text='Top-left row index for this entry (0-based)')),
                ('col', models.PositiveIntegerField(help_text='Top-left col index for this entry (0-based)')),
                ('length', models.PositiveIntegerField(help_text='Number of letters in the answer')),
                ('crossword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.crossword')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit_seconds', models.PositiveIntegerField(default=0, help_text='0 means no enforced time limit')),
                ('crossword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_sessions', to='api.crossword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'crossword')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('fastest_seconds', models.PositiveIntegerField(default=0, help_text='0 means not completed yet')),
                ('completed', models.BooleanField(default=False)),
                ('accuracy', models.FloatField(default=0.0)),
                ('crossword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='api.crossword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed', 'fastest_seconds', '-accuracy', '-updated_at'],
                'unique_together': {('user', 'crossword')},
            },
        ),
        migrations.CreateModel(
            name='AnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('submitted_answer', models.CharField(max_length=128)),
                ('correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.crosswordentry')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.puzzlesession')),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('session', 'entry')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='crosswordentry',
            unique_together={('crossword', 'number', 'direction')},
        ),
    ]
